services:
  businessweb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - dokploy-network
      - client-mailpit-qf3zat
    labels:
      - "traefik.http.services.client-businessweb-lqmi8v-32-web.loadbalancer.server.port=4000"

networks:
  dokploy-network:
    external: true
  client-mailpit-qf3zat:
    external: true