services:
  businessweb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NGINX_HOST=businessweb.guillaume-lcte.fr
      - NGINX_PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.businessweb.rule=Host(`businessweb.guillaume-lcte.fr`)"
      - "traefik.http.services.businessweb.loadbalancer.server.port=8080"
      - "traefik.http.routers.businessweb.tls=true"
      - "traefik.http.routers.businessweb.tls.certresolver=letsencrypt"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true 