version: '3.8'

services:
  businessweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: businessweb-site
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      timeout: 5s
      interval: 30s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.businessweb.rule=Host(`businessweb.guillaume-lcte.fr`)"
      - "traefik.http.services.businessweb.loadbalancer.server.port=8080"
      - "traefik.http.routers.businessweb.tls=true"
      - "traefik.http.routers.businessweb.tls.certresolver=letsencrypt"
    networks:
      - businessweb-network

networks:
  businessweb-network:
    driver: bridge 