services:
  businessweb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - dokploy-network
      - client-mailpit-qf3zat

networks:
  dokploy-network:
    external: true
  client-mailpit-qf3zat:
    external: true